version: '3'

services:
  web:
    image: nginx
    container_name: docker-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/usr/share/nginx/html:ro
    ports:
      - '80:80'
